### ISSUE TITLE
firmware-util.sh: ./firmware.sh: line 8: syntax error: unexpected "("

### ISSUE THREAD

**Issue by sd26** [MattDevo/scripts#11]
Using username "root".
root@192.168.1.137's password:
##############################################
#                 LibreELEC                  #
#            http://libreelec.tv             #
##############################################

LibreELEC (community) Version: devel-20160720210643-#0720-g19b259b
LibreELEC git: 19b259b906aad7f2c24911f18b7d4734e37e7e44

kodi-tv:~ # cd; curl -L -O http://mrchromebox.tech/firmware-util.sh && bash firmware-util.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    293      0 --:--:-- --:--:-- --:--:--   293
100   178  100   178    0     0    102      0  0:00:01  0:00:01 --:--:--     0
100   257    0   257    0     0    116      0 --:--:--  0:00:02 --:--:--   116
100  1007  100  1007    0     0    385      0  0:00:02  0:00:02 --:--:-- 10275
firmware-util.sh: ./firmware.sh: line 8: syntax error: unexpected "("

LibreELEC 8.0 test build. No problems with previous firmware update scripts.

**Comment by MattDevo** [comment]
You can't run either the Kodi E-Z Setup Script or the ChromeOS Firmware Utility Script from under Open/LibreELEC, since they don't have a full bash shell, and therefore don't support the functionality needed.  

The previous "standalone firmware updater script" which did work under Open/LibreELEC is no longer supported, since it's not practical to do so given the range of devices supported now.
